module.exports =
    # Blacklisted User-Agent strings.
    'useragent': [
        {
            # These user agent strings occur at the beginning of the line.
            fn: (check, rule) -> not check or check.indexOf(rule) is 0
            response:
                statusCode: 403
                body: 'You do not have permission to access this server'
                log: 'User-Agent was found on blacklist'
            rules: [
                '8484 Boston Project',
                'AESOP_com_SpiderMan',
                'Alexibot',
                'BackDoorBot',
                'BackWeb',
                'Baiduspider',
                'BatchFTP',
                'Bigfoot',
                'Black.Hole',
                'BlackWidow',
                'BlowFish',
                'Bork-edition',
                'Bot mailto:craftbot@yahoo.com',
                'BotALot',
                'BrowserEmulator/',
                'BuiltBotTough',
                'Bullseye',
                'BunnySlippers',
                'Cegbfeieh',
                'CheeseBot',
                'CherryPicker',
                'ChinaClaw',
                'CopyRightCheck',
                'Crescent',
                'Curl',
                'Custo',
                'DA',
                'DIIbot',
                'DISCo',
                'Diamond',
                'Digger',
                'DittoSpyder',
                'Download',
                'Drip',
                'EasyDL',
                'EirGrabber',
                'Email Siphon',
                'EmailCollector',
                'EmailSiphon',
                'EmailWolf',
                'EroCrawler',
                'Exabot',
                'Express WebPictures',
                'ExtractorPro',
                'EyeNetIE',
                'Fetch API Request',
                'FileHound',
                'FlashGet',
                'Foobot',
                'Forum Poster',
                'FrontPage',
                'GT::WWW',
                'GetRight',
                'GetSmart',
                'GetWeb!',
                'Go!Zilla',
                'Go-Ahead-Got-It',
                'GrabNet',
                'Grafula',
                'HMView',
                'HTTP::Lite',
                'HTTrack',
                'Harvest',
                'HttpProxy',
                'IBM EVV',
                'ISC Systems iRc',
                'IlseBot',
                'Image ',
                'Image Stripper',
                'Image Sucker',
                'InfoNaviRobot',
                'InfoTekies',
                'Intelliseek',
                'InterGET',
                'Internet Explorer',
                'Internet Ninja',
                'Iria',
                'JOC',
                'Jakarta',
                'Java',
                'JennyBot',
                'JetCar',
                'JustView',
                'Jyxobot',
                'Kenjin.Spider',
                'Keyword.Density',
                'LNSpiderguy',
                'LWP',
                'LWP::Simple',
                'LeechFTP',
                'LexiBot',
                'LinkScan/8.1a.Unix',
                'LinkWalker',
                'LinkextractorPro',
                'MFC_Tear_Sample',
                'MIDown tool',
                'MIIxpc',
                'MJ12bot/v1.0.8',
                'MSIE',
                'MVAClient',
                'Mag-Net',
                'Magnet',
                'MarkWatch',
                'Mass Downloader',
                'Mata.Hari',
                'Memo',
                'Microsoft Internet Explorer/',
                'Microsoft URL',
                'Microsoft.URL',
                'Mirror',
                'Missigua',
                'Missigua Locator',
                'Mister PiX',
                'Morfeus',
                'Movable Type',
                'Mozilla.*NEWT',
                'Mozilla/0',
                'Mozilla/1',
                'Mozilla/2',
                'Mozilla/3',
                'Mozilla/4.0 (Hydra)',
                'Mozilla/4.0(',
                'Mozilla/4.0+(compatible;+',
                'NAMEPROTECT',
                'NG',
                'NICErsPRO',
                'NPbot',
                'Navroad',
                'NearSite',
                'Nessus',
                'Net Vampire',
                'NetAnts',
                'NetMechanic',
                'NetSpider',
                'NetZIP',
                'Netcraft',
                'NextGenSearchBot',
                'NimbleCrawler',
                'Ninja',
                'Nutch',
                'Nutscrape/',
                'Octopus',
                'Offline Explorer',
                'Offline Navigator',
                'OmniExplorer',
                'Openfind',
                'Opera/9.64(',
                'OutfoxBot',
                'PECL::HTTP',
                'PHP',
                'PHP version tracker',
                'PageGrabber',
                'Papa Foto',
                'Pockey',
                'ProPowerBot/2.14',
                'ProWebWalker',
                'Pump',
                'PussyCat ',
                'PycURL',
                'Python-urllib',
                'QueryN.Metasearch',
                'RMA',
                'ReGet',
                'RealDownload',
                'RepoMonkey',
                'SiteSnagger',
                'SlySearch',
                'SmartDownload',
                'Snake',
                'Snapbot',
                'Snoopy',
                'SpaceBison',
                'SpankBot',
                'Sqworm',
                'Super Happy Fun ',
                'SuperBot',
                'SuperHTTP',
                'Surfbot',
                'Szukacz/1.4',
                'Teleport',
                'Telesoft',
                'The.Intraformant',
                'TheNomad',
                'TightTwatBot',
                'Titan',
                'TrackBack/',
                'True_Robot',
                'TurnitinBot',
                'TurnitinBot/1.5',
                'URI::Fetch',
                'URLy.Warning',
                'User Agent',
                'User-Agent',
                'VCI',
                'Vacuum',
                'VoidEYE',
                'WISENutbot',
                'WWW-Collector-E',
                'WWWOFFLE',
                'Web Image Collector',
                'Web Sucker',
                'Web.Image.Collector',
                'WebAuto',
                'WebBandit',
                'WebCopier',
                'WebEMailExtrac.*',
                'WebEnhancer',
                'WebFetch',
                'WebGo IS',
                'WebLeacher',
                'WebReaper',
                'WebSauger',
                'WebSite',
                'WebSite-X Suite',
                'WebStripper',
                'WebWhacker',
                'WebZIP',
                'Webclipping.com',
                'WebmasterWorldForumBot',
                'Website Quester',
                'Website eXtractor',
                'Webster',
                'Wget',
                'Widow',
                'Winnie Poh',
                'Wordpress',
                'Xaldon',
                'Xenu',
                'Zend_Http_Client',
                'Zeus',
                'Zyborg',
                'adwords',
                'asterias',
                'attach',
                'autoemailspider',
                'blogsearchbot-martin',
                'compatible ;',
                'core-project/',
                'cosmos',
                'curl',
                'dragonfly',
                'eCatch',
                'ebingbong',
                'ecollector',
                'flunky',
                'gotit',
                'grub crawler',
                'heritrix',
                'hloader',
                'http client',
                'httplib',
                'humanlinks',
                'ia_archiver',
                'larbin',
                'lftp',
                'libWeb/clsHTTP',
                'libwww',
                'likse',
                'lwp',
                'lwp-trivial',
                'moget',
                'panscient.com',
                'pavuk',
                'pcBrowser',
                'psbot',
                'psycheclone',
                'sogou',
                'spanner',
                'sqlmap/',
                'suzuran',
                'tAkeOut',
                'toCrawl/UrlDispatcher',
                'turingos',
                'urllib',
                'user',
                'w3af'
            ]
        }, {
            # These user agent strings occur anywhere within the line.
            fn: (check, rule) -> check.indexOf(rule) isnt -1
            response:
                statusCode: 403
                body: 'You do not have permission to access this server'
                log: 'User-Agent was found on blacklist'
            rules: [
                '.NET CLR 1)',
                '.NET CLR1',
                '; Widows ',
                '<sc',
                'Anonymouse.org',
                'Bad Behavior Test',
                'Bandit',
                'Buddy',
                'Collector',
                'Copier',
                'DTS Agent',
                'Downloader',
                'Email Extractor',
                'Extractor',
                'Firebird/',
                'Gecko/25',
                'Google Wireless Transcoder',
                'Grabber',
                'HTTrack',
                'Havij',
                'ISC Systems iRc Search ',
                'Indy Library',
                'InterGET',
                'Internet Ninja',
                'JOC Web Spider',
                'JetCar',
                'LeechFTP',
                'MIDown tool',
                'MSIE 7.0;  Windows NT 5.2',
                'Mass Downloader',
                'Microsoft URL Control',
                'Ming Mong',
                'Missigua',
                'Mister PiX',
                'Murzillo compatible',
                'Navroad',
                'NearSite',
                'Net Vampire',
                'NetAnts',
                'NetSpider',
                'NetZIP',
                'Nikto/',
                'Octopus',
                'Offline Explorer',
                'Offline Navigator',
                'POE-Component-Client',
                'PageGrabber',
                'Papa Foto',
                'Perman Surfer',
                'ReGet',
                'RealDownload',
                'Reaper',
                'Recorder',
                'Siphon',
                'SiteSnagger',
                'SmartDownload',
                'Stripper',
                'Sucker',
                'SuperBot',
                'SuperHTTP',
                'Surfbot',
                'Teh Forest Lobster',
                'Teleport Pro',
                'Turing Machine',
                'Ubuntu/9.25',
                'User-agent: ',
                'VoidEYE',
                'WEP Search',
                'WISEbot',
                'WISEnutbot',
                'WWWOFFLE',
                'Web Image Collector',
                'Web Sucker',
                'WebAuto',
                'WebCopier',
                'WebFetch',
                'WebGo IS',
                'WebLeacher',
                'WebReaper',
                'WebSauger',
                'WebStripper',
                'WebWhacker',
                'WebZIP',
                'WebaltBot',
                'Website Quester',
                'Website eXtractor',
                'Wells Search II',
                'Whacker',
                'Widow',
                'Win 9x 4.90',
                'Win95',
                'Win98',
                'WinME',
                'Windows 3',
                'Windows 95',
                'Windows 98',
                'Windows NT 4',
                'Windows NT 5.0;)',
                'Windows NT 5.1;)',
                'Windows NT;',
                'Windows XP 5',
                'WordPress/4.01',
                'Xaldon WebSpider',
                'Xedant Human Emulator',
                'Zeus',
                'ZmEu',
                'a href=',
                'compatible ; MSIE',
                'compatible-',
                'grub-client',
                'hanzoweb',
                'larbin',
                'libghttp',
                'pavuk',
                'pcBrowser',
                'sitecheck.internetseer.com',
                'tAkeOut',
                'unspecified.mail'
            ]
        }, {
            # These are regular expression matches.
            fn: (check, rule) -> check.match new RegExp rule
            response:
                statusCode: 403
                body: 'You do not have permission to access this server'
                log: 'User-Agent was found on blacklist'
            rules: [
                /^[A-Z]{10}$/,
                /[A-Z][a-z]{3,} [a-z]{4,} [a-z]{4,}/,
                /[bcdfghjklmnpqrstvwxz ]{8,}/,
                /MSIE [2345]/,
                /^Mozilla$/
            ]
        }
    ]

    # Blacklisted URL strings
    'url': [
        {
            # These strings are considered case-insensitive.
            fn: (check, rule) -> check.match rule, 'i'
            response:
                statusCode: 403
                body: 'You do not have permission to access this server'
                log: 'URL pattern found on blacklist'
            rules: [
                /0x31303235343830303536/,
                /\.\.\//,
                /\.\.\\/,
                /%60information_schema%60/,
                /\+%2F\*%21/,
                /%27\-\-/,
                /%27%20\-\-/,
                /%27%23/,
                /%27%20%23/,
                /benchmark%28/,
                /insert\+into\+/,
                /r3dm0v3/,
                /select\+1\+from/,
                /union\+all\+select/,
                /union\+select/,
                /waitfor\+delay\+/,
                /w00tw00t/,
                /((\%3D)|(=))[^\n]*((\%27)|(\')|(\-\-)|(\%3B)|(;))/,
                /\w*((\%27)|(\'))((\%6F)|o|(\%4F))((\%72)|r|(\%52))/,
                /((\%3C)|<)((\%2F)|\/)*[a-z0-9\%]+((\%3E)|>)/,
                /((\%3C)|<)((\%69)|i|(\%49))((\%6D)|m|(\%4D))((\%67)|g|(\%47))[^\n]+((\%3E)|>)/,
                /((\%3C)|<)[^\n]+((\%3E)|>)/
            ]
        }
    ]